print ("WELCOME TO MAD-LIB")
print("ANSWER THESE QUESTIONS")
print("")
name1 = input("what is your name?")
person1 = input("enter a famous person?")
awardshow1 = input("enter a type of award show")
help1 = input("enter a random act in the past tense e.g. donated to charity/ate dinner/went to school")
project1 = input("enter a creation e.g. an album/a movie/a book")
student1 = input("enter a students name from trinity school")
adjective1 = input("enter a random adjective e.g. strange/musty/massive")
videogame1 = input("enter a random videogame")
adjective2 = input("enter a random adjective again")

print("Well" ,name1, "did you know that the global superstar" ,person1, "was actually invited to the" ,awardshow1, "because he" ,help1, "and made" ,project1, ". He also met" ,student1, "who is very" ,adjective1, "and always plays" ,videogame1, "because he is" ,adjective2, ".")
